### PR TITLE
Make customizable :load_feed_products

### PR DESCRIPTION
**Pull request by VitaliyAdamkov**

### CODE REVIEW

**Comment by jarednorman** [comment]
I like the change to use a `before_action`, but I don't understand why you moved from a `Module#prepend` to a `class_eval`. Could you provide some clarification? It seems like we could switch to a `before_action` while still using `Module#prepend` and maintain the benefits over `class_eval`.

**Comment by VitaliyAdamkov** [comment]
> I like the change to use a `before_action`, but I don't understand why you moved from a `Module#prepend` to a `class_eval`. Could you provide some clarification? It seems like we could switch to a `before_action` while still using `Module#prepend` and maintain the benefits over `class_eval`.

Cause I need to use my own `load_feed_products` method for the case, at mine `app/controllers/products_controller_decorator.rb`.
If using `Module#prepend` this overwrite is unaccessible. I've placed debug breakpoints into `load_feed_products` and `index` at gem's `products_controller_decorator` and at the methods with the same names at mine `products_controller_decorator` and flow was:
1) `load_feed_products` at gem's decorator
2) `index` at gem's decorator
3) `index` at mine decorator
`load_feed_products` at mine decorator didn't run at all.

What are the benefits of using `Module#prepend`?

**Comment by jarednorman** [comment]
The advantage of `prepend` over `class_eval` is that `prepend` gives the ability to call `super` and avoid copy-pasting code when overriding extensions. For this reason the Solidus community has largely decided that is preferable, as there aren't really any downsides.

I suspect the issue you ran into was that you used `class_eval` to try to override it. If you did, you'll just need to change your decorator to use `prepend` and you'll be good to go.

Can I ask why you needed to override them method? I'm just curious, for the sake of understanding how people are using this extension.

**Comment by jarednorman** [comment]
There's also some more good information [here](https://stembolt.com/blog/class_eval-and-the-terrible-horrible-no-good-very-bad-day/).

**Pull request closed without merging**
