### PR TITLE
Relax solidus_support dependency

### PR DESCRIPTION
**Pull request by kennyadsl**
Also, closes #52

### CODE REVIEW

**Comment by cyberious** [comment]
We should get this in, the gem release is broken for my needs with errors of 

~~~
expected file /Users/cyberious/repos/company_x/site/vendor/ruby/2.6.0/gems/solidus_product_feed-1.0.0/app/controllers/spree/products_controller_decorator.rb to define constant Spree::ProductsControllerDecorator
~~~

**Comment by aldesantis** [comment]
@cyberious I don't have access to release this gem, but I have pushed a couple of commits in master that should fix any compatibility issues with Zeitwerk. Try pulling the gem from GitHub and let me know how it works!

**Comment by aldesantis** [comment]
@kennyadsl can we release a new version? Happy to do it if you give me access on RubyGems.

**Comment by kennyadsl** [comment]
This gem hasn't been released in several years. I think until we have a clear policy around that we can keep using the GitHub version. I would not even know which kind of release is needed (major/minor/path) honestly.

**Comment by aldesantis** [comment]
@kennyadsl asking because we need to start releasing new versions of all extensions anyway, so we need to start somewhere. 😛 Happy to try and figure out what the next version should be if you provide access to RubyGems.

**Comment by kennyadsl** [comment]
@aldesantis Added, thanks!

**Comment by aldesantis** [comment]
@cyberious I have just released 1.1.0 which should contain all the fixes.

**Pull request merged**
